### ISSUE TITLE
Need isCrowd flag for Coco mAP protocol

### ISSUE THREAD

**Issue by mkmsftgit** [microsoft/vision-datasets#26]
Ground truth bounding box information needs to have "iscrowd" flag to be able to use in Coco evaluation protocol.

https://github.com/microsoft/vision-datasets/blob/716bbe4b97827aeccdedd7dbceaf69783b841657/vision_datasets/common/manifest_dataset.py#L48

**Comment by pj-ms** [comment]
addressed in this PR: https://github.com/microsoft/vision-datasets/pull/32
